#!/usr/bin/env python3
"""
Generate PNG screenshots of each slide from a PPTX file.

Uses LibreOffice (soffice) to convert to PDF, then pdftoppm (poppler) to render PNGs.

Usage:
    python generate-screenshots.py <input.pptx> [output_dir]

Output:
    output_dir/screenshots/screenshot_1.png, screenshot_2.png, etc.

Requirements:
    - LibreOffice (soffice or libreoffice on PATH)
    - pdftoppm from poppler (brew install poppler / apt install poppler-utils)
"""

import sys
import os
import shutil
import subprocess
import tempfile
from pathlib import Path


def check_tools():
    """Check that required tools are available."""
    soffice = shutil.which('soffice') or shutil.which('libreoffice')
    pdftoppm = shutil.which('pdftoppm')

    if not soffice:
        print("Error: LibreOffice not found.")
        print("  macOS:   brew install --cask libreoffice")
        print("  Ubuntu:  sudo apt install libreoffice")
        return None, None

    if not pdftoppm:
        print("Error: pdftoppm not found (part of poppler).")
        print("  macOS:   brew install poppler")
        print("  Ubuntu:  sudo apt install poppler-utils")
        return soffice, None

    return soffice, pdftoppm


def generate_screenshots(input_path, output_dir, dpi=150):
    """Generate slide screenshots from a PPTX file."""
    input_path = Path(input_path)
    output_dir = Path(output_dir)

    if not input_path.exists():
        print(f"Error: File not found: {input_path}")
        sys.exit(1)

    soffice, pdftoppm = check_tools()
    if not soffice or not pdftoppm:
        sys.exit(1)

    screenshots_dir = output_dir / "screenshots"
    screenshots_dir.mkdir(parents=True, exist_ok=True)

    print(f"Input: {input_path}")
    print(f"Output: {screenshots_dir}")
    print(f"DPI: {dpi}")
    print()

    with tempfile.TemporaryDirectory() as tmpdir:
        # Step 1: PPTX → PDF via LibreOffice
        print("Converting PPTX to PDF via LibreOffice...")
        try:
            result = subprocess.run(
                [soffice, '--headless', '--convert-to', 'pdf', '--outdir', tmpdir, str(input_path)],
                capture_output=True, text=True, timeout=300
            )
            if result.returncode != 0:
                print(f"Error: LibreOffice conversion failed:\n{result.stderr}")
                sys.exit(1)
        except subprocess.TimeoutExpired:
            print("Error: LibreOffice conversion timed out (300s)")
            sys.exit(1)

        pdf_files = list(Path(tmpdir).glob('*.pdf'))
        if not pdf_files:
            print("Error: No PDF generated by LibreOffice")
            sys.exit(1)
        pdf_path = pdf_files[0]
        print(f"  PDF generated: {pdf_path.stat().st_size / 1024 / 1024:.1f} MB")

        # Step 2: PDF → PNGs via pdftoppm
        print(f"Rendering slides to PNG at {dpi} DPI...")
        try:
            result = subprocess.run(
                [pdftoppm, '-png', '-r', str(dpi), str(pdf_path), str(Path(tmpdir) / 'slide')],
                capture_output=True, text=True, timeout=600
            )
            if result.returncode != 0:
                print(f"Error: pdftoppm failed:\n{result.stderr}")
                sys.exit(1)
        except subprocess.TimeoutExpired:
            print("Error: pdftoppm timed out (600s)")
            sys.exit(1)

        # Step 3: Rename and copy to output
        generated = sorted(Path(tmpdir).glob('slide-*.png'))
        for i, src in enumerate(generated, 1):
            dest = screenshots_dir / f"screenshot_{i}.png"
            shutil.copy2(str(src), str(dest))

        print(f"\nDone! Generated {len(generated)} screenshots in {screenshots_dir}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate-screenshots.py <input.pptx> [output_dir]")
        print("  output_dir defaults to 'sourcematerials/'")
        sys.exit(1)

    input_path = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else 'sourcematerials'

    generate_screenshots(input_path, output_dir)


if __name__ == '__main__':
    main()
